import assert from 'node:assert/strict'
import { readFile } from 'node:fs/promises'
import test from 'node:test'

test('keeps teacher tools inside one workspace without an archive action', async () => {
  const dashboardSource = await readFile(
    new URL('../../src/pages/HRDashboard.jsx', import.meta.url),
    'utf8',
  )
  const coursesSource = await readFile(
    new URL('../../src/components/CoursFolders.jsx', import.meta.url),
    'utf8',
  )

  assert.doesNotMatch(dashboardSource, />\s*Archiver\s*</)
  assert.doesNotMatch(dashboardSource, /function CardToolModal/)
  assert.match(dashboardSource, /function TeacherToolPanel/)
  assert.match(dashboardSource, /const \[activeTool, setActiveTool\] = useState\(null\)/)
  assert.match(dashboardSource, /activeTool === 'students'/)
  assert.match(dashboardSource, /label: 'Mail\(s\) d’invitation'/)
  assert.match(dashboardSource, /key: 'students', label: 'Élèves'/)
  assert.match(dashboardSource, /activeTool === 'invitations'/)
  assert.match(dashboardSource, /function InvitationsToolContent/)
  assert.match(dashboardSource, /activeTool === 'attendance'/)
  assert.doesNotMatch(dashboardSource, /key: 'audios'/)
  assert.doesNotMatch(dashboardSource, /activeTool === 'audios'/)
  assert.doesNotMatch(dashboardSource, /activeTool === 'pdf'/)
  assert.doesNotMatch(dashboardSource, /key: 'pdf'/)
  assert.match(dashboardSource, /activeTool === 'planning'/)
  assert.match(dashboardSource, /Prochaines séances/)
  assert.match(dashboardSource, /Anciennes séances \(\{pastCourseSessions\.length\}\)/)
  assert.doesNotMatch(dashboardSource, /<Icon name="history" className="text-xl" \/>/)
  assert.match(dashboardSource, /<details className="group mt-4 border-t pt-2"/)
  assert.doesNotMatch(dashboardSource, /<details[^>]*\sopen(?:=|\s|>)/)
  assert.match(dashboardSource, /<CoursFoldersModal[\s\S]*?embedded/)
  assert.doesNotMatch(
    coursesSource,
    /className="mb-5 border-b pb-4"/,
  )
  assert.match(dashboardSource, /max-w-xl/)
  assert.doesNotMatch(dashboardSource, /teacher-robot-float/)
  assert.doesNotMatch(dashboardSource, /max-w-\[1180px\]/)
  assert.match(coursesSource, /embedded = false/)
  assert.match(coursesSource, /embedded \? 'h-full min-h-0 w-full'/)
  assert.doesNotMatch(dashboardSource, /activeTool \? 'hidden' : 'flex min-h-\[430px\]'/)
  assert.doesNotMatch(dashboardSource, /activeTool \? 'hidden sm:flex'/)
  assert.doesNotMatch(dashboardSource, /absolute left-5 top-5[\s\S]*?rosterMeta\.label/)
  assert.match(coursesSource, /Télécharger le PDF/)
  assert.doesNotMatch(coursesSource, /Retour aux cours/)
  assert.match(coursesSource, /view === 'documents' \? handleBackToFolders/)
  assert.match(coursesSource, /embedded \? 'gap-2 px-3 pb-3 pt-5'/)
  assert.match(coursesSource, /aria-label=\{`Consulter \$\{item\.filename\}`\}/)
  assert.doesNotMatch(coursesSource, /name="content_cut"/)
  assert.doesNotMatch(coursesSource, />\s*Support PDF de la journée\s*</)
  assert.doesNotMatch(coursesSource, /Créé à la fin de la pipeline, sans balises techniques/)
  assert.doesNotMatch(coursesSource, /Support de la journée \{selectedCourseMaterial\.session_index\}/)
  assert.match(coursesSource, /Support PDF prêt/)
  assert.match(coursesSource, /fin de la pipeline/)
  assert.doesNotMatch(coursesSource, /avec les audios à H-48/)
  assert.match(coursesSource, /course-materials/)
  assert.match(coursesSource, /next-course-selection/)
  assert.match(coursesSource, /session_id: Number\(selectedSessionId\)/)
  assert.match(coursesSource, /createPortal/)
  assert.match(coursesSource, /role="dialog"/)
  assert.match(coursesSource, /aria-modal="true"/)
  assert.match(coursesSource, /Cours prévu/)
  assert.match(coursesSource, /Enregistrer pour cette séance/)
  assert.match(coursesSource, /Les séances suivantes conservent automatiquement le cours prévu dans leur progression/)
  assert.match(coursesSource, />\s*Jour \{index \+ 1\}\s*</)
  assert.doesNotMatch(coursesSource, /Jour \{index \+ 1\} — \{folder\.name\}/)
  assert.match(coursesSource, /Choisir le prochain cours/)
  assert.match(coursesSource, /Solution de dernier recours/)
  assert.match(coursesSource, /contactez le support/)
  assert.match(coursesSource, /Cliquez sur le bouton ci-dessous pour choisir le prochain cours/)
  assert.match(coursesSource, /uniquement pendant la séquence indiquée/)
  assert.match(coursesSource, /showFillInfo && typeof document !== 'undefined' && createPortal/)
  assert.doesNotMatch(coursesSource, /lg:sticky lg:top-0 lg:z-auto/)
  assert.doesNotMatch(coursesSource, /inline-flex min-h-10 min-w-0 items-center justify-center/)
  assert.match(coursesSource, /role="complementary"/)
  assert.match(coursesSource, /Rétracter le panneau d’information/)
  assert.match(coursesSource, /Retour à la journée/)
  assert.match(coursesSource, /Sous-page du script TTS généré/)
  assert.ok(
    coursesSource.indexOf('Télécharger le PDF') > coursesSource.indexOf('Sous-page du script TTS généré'),
    'le téléchargement PDF doit se trouver dans la sous-page du script TTS',
  )
  assert.doesNotMatch(coursesSource, /Modale script TTS généré/)
  assert.doesNotMatch(coursesSource, />\s*Script TTS généré\s*</)
  assert.match(coursesSource, /onScriptViewChange\?\.\(contentScriptOpen\)/)
  assert.match(dashboardSource, /courseScriptExpanded \? 'max-w-none px-0'/)
  assert.match(dashboardSource, /h-\[calc\(100dvh-7rem\)\] min-h-\[44rem\]/)
  assert.match(dashboardSource, /selectedTeacherId \? 'max-w-\[90rem\] grid-cols-1'/)
  assert.match(coursesSource, /flex min-h-0 flex-1 flex-col md:flex-row/)
  assert.match(coursesSource, /md:w-56 md:border-b-0 md:border-r/)
  assert.match(coursesSource, /ml-auto flex flex-wrap items-center justify-end gap-2/)
  assert.match(coursesSource, />\s*Modifier\s*</)
  assert.match(coursesSource, /aria-label="Contenu affiché dans la liste"/)
  assert.match(coursesSource, />\s*Cours \+ pauses\s*</)
  assert.match(coursesSource, /Aucune pause pour cette journée\./)
  assert.match(coursesSource, /br\.type !== 'qa' && br\.type !== 'jointure'/)
  assert.doesNotMatch(coursesSource, /Générer \{expectedCourseLabel\}/)
  assert.doesNotMatch(coursesSource, />\s*Générer tout\s*</)
  assert.doesNotMatch(coursesSource, /handleGeneratePlaylistItem\(active\.filename, 'gtts'\)/)
  assert.doesNotMatch(coursesSource, /handleGeneratePlaylistItem\(active\.filename, 'fish_audio'\)/)
  assert.doesNotMatch(coursesSource, /handleGeneratePlaylistItem\(br\.filename, 'gtts'\)/)
  assert.doesNotMatch(coursesSource, /handleGeneratePlaylistItem\(br\.filename, 'fish_audio'\)/)
  assert.doesNotMatch(coursesSource, /coursePlanNote/)
  assert.doesNotMatch(coursesSource, /Résumé du dernier audio lu/)
  assert.doesNotMatch(coursesSource, /Mots input/)
  assert.doesNotMatch(coursesSource, /Mots Fish/)
  assert.doesNotMatch(coursesSource, /event_repeat/)
  assert.doesNotMatch(coursesSource, /ordre chronologique/)
  assert.doesNotMatch(coursesSource, /drag_indicator/)
  assert.doesNotMatch(coursesSource, /handleFolderDrag/)
  assert.doesNotMatch(coursesSource, /document_count/)
  assert.doesNotMatch(coursesSource, /tp-crcd-thumbnail/)
  assert.match(coursesSource, /Audio prêt/)
  assert.doesNotMatch(coursesSource, />\s*Réutiliser un cours\s*</)
  assert.match(coursesSource, /Audios prêts/)
  assert.match(dashboardSource, /Prochaines séances/)
  assert.match(dashboardSource, /générées automatiquement 72 heures avant leur début/)
})

test('offers recruitment from the empty teacher roster', async () => {
  const dashboardSource = await readFile(
    new URL('../../src/pages/HRDashboard.jsx', import.meta.url),
    'utf8',
  )

  assert.match(dashboardSource, /platforms\.length === 0/)
  assert.match(dashboardSource, /Aucun professeur recruté/)
  assert.match(dashboardSource, /onClick=\{onRecruit\}/)
  assert.match(dashboardSource, />\s*Recruter un professeur\s*</)
  assert.match(dashboardSource, /onRecruit=\{showRecruitView\}/)
})
